namespace Crystal.Mmi.HardwareFeatures.ParallelPort;

public record ParallelPortMetrics(
  ushort? Availability,
  ushort[]? Capabilities,
  string? CapabilityDescriptions,
  string? Caption,
  uint? ConfigManagerErrorCode,
  bool? ConfigManagerUserConfig,
  string? CreationClassName,
  string? Description,
  string? DeviceID,
  bool? DMASupport,
  bool? ErrorCleared,
  string? ErrorDescription,
  DateTime? InstallDate,
  uint? LastErrorCode,
  uint? MaxNumberControlled,
  string? Name,
  bool? OSAutoDiscovered,
  string? PNPDeviceID,
  ushort[]? PowerManagementCapabilities,
  bool? PowerManagementSupported,
  ushort? ProtocolSupported,
  string? Status,
  ushort? StatusInfo,
  string? SystemCreationClassName,
  string? SystemName,
  DateTime? TimeOfLastReset
);
