namespace Crystal.Provider.Mmi.HardwareFeatures.CacheMemory;

public record CacheMemoryMetrics(
  ushort? Access,
  string? AdditionalErrorData,
  ushort? Associativity,
  ushort? Availability,
  ulong? BlockSize,
  ushort? CacheSpeed,
  ushort? CacheType,
  string? Caption,
  uint? ConfigManagerErrorCode,
  bool? ConfigManagerUserConfig,
  bool? CorrectableError,
  string? CreationClassName,
  ushort[]? CurrentSRAM,
  string? Description,
  string? DeviceID,
  ulong? EndingAddress,
  ushort? ErrorAccess,
  ulong? ErrorAddress,
  bool? ErrorCleared,
  ushort? ErrorCorrectType,
  string? ErrorData,
  ushort? ErrorDataOrder,
  string? ErrorDescription,
  ushort? ErrorInfo,
  string? ErrorMethodology,
  ulong? ErrorResolution,
  DateTime? ErrorTime,
  uint? ErrorTransferSize,
  uint? FlushTimer,
  DateTime? InstallDate,
  uint? InstalledSize,
  uint? LastErrorCode,
  ushort? Level,
  uint? LineSize,
  string? Location,
  uint? MaxCacheSize,
  string? Name,
  ulong? NumberOfBlocks,
  string? OtherErrorDescription,
  string? PNPDeviceID,
  ushort[]? PowerManagementCapabilities,
  bool? PowerManagementSupported,
  string? Purpose,
  ushort? ReadPolicy,
  ushort? ReplacementPolicy,
  ulong? StartingAddress,
  string? Status,
  ushort? StatusInfo,
  ushort[]? SupportedSRAM,
  string? SystemCreationClassName,
  bool? SystemLevelAddress,
  string? SystemName,
  ushort? WritePolicy)
{
    public double? InstalledSizeInMB => InstalledSize is null ? null : Math.Round(InstalledSize.Value / 1024d, 2);
    public double? MaxCacheSizeInMB => MaxCacheSize is null ? null : Math.Round(MaxCacheSize.Value / 1024d, 2);
    public string? CacheTypeName => CacheType switch { 1 => "Other", 2 => "Unknown", 3 => "Instruction", 4 => "Data", 5 => "Unified", _ => null };
    public string? LevelName => Level switch { 3 => "L1", 4 => "L2", 5 => "L3", _ => null };
    public string? AssociativityName => Associativity switch { 1 => "Other", 2 => "Unknown", 3 => "Direct Mapped", 4 => "2-way Set-Associative", 5 => "4-way Set-Associative", 6 => "Fully Associative", 7 => "8-way Set-Associative", 8 => "16-way Set-Associative", _ => null };
}
