using Crystal.Provider.Mmi.Wmi;
namespace Crystal.Provider.Mmi.HardwareFeatures.CacheMemory;
internal static class WmiCacheMemory
{
    public const string ClassName = WmiClasses.CacheMemory;
    public const string Caption = CommonWmiProperties.Caption;
    public const string Description = CommonWmiProperties.Description;
    public const string Name = CommonWmiProperties.Name;
    public const string Status = CommonWmiProperties.Status;
    public const string DeviceID = CommonWmiProperties.DeviceId;
    public const string PNPDeviceID = CommonWmiProperties.PnpDeviceId;
    public const string Access = nameof(Access); public const string AdditionalErrorData = nameof(AdditionalErrorData); public const string Associativity = nameof(Associativity); public const string Availability = nameof(Availability); public const string BlockSize = nameof(BlockSize); public const string CacheSpeed = nameof(CacheSpeed); public const string CacheType = nameof(CacheType); public const string ConfigManagerErrorCode = nameof(ConfigManagerErrorCode); public const string ConfigManagerUserConfig = nameof(ConfigManagerUserConfig); public const string CorrectableError = nameof(CorrectableError); public const string CreationClassName = nameof(CreationClassName); public const string CurrentSRAM = nameof(CurrentSRAM); public const string EndingAddress = nameof(EndingAddress); public const string ErrorAccess = nameof(ErrorAccess); public const string ErrorAddress = nameof(ErrorAddress); public const string ErrorCleared = nameof(ErrorCleared); public const string ErrorCorrectType = nameof(ErrorCorrectType); public const string ErrorData = nameof(ErrorData); public const string ErrorDataOrder = nameof(ErrorDataOrder); public const string ErrorDescription = nameof(ErrorDescription); public const string ErrorInfo = nameof(ErrorInfo); public const string ErrorMethodology = nameof(ErrorMethodology); public const string ErrorResolution = nameof(ErrorResolution); public const string ErrorTime = nameof(ErrorTime); public const string ErrorTransferSize = nameof(ErrorTransferSize); public const string FlushTimer = nameof(FlushTimer); public const string InstallationDate = nameof(InstallationDate); public const string InstalledSize = nameof(InstalledSize); public const string LastErrorCode = nameof(LastErrorCode); public const string Level = nameof(Level); public const string LineSize = nameof(LineSize); public const string Location = nameof(Location); public const string MaxCacheSize = nameof(MaxCacheSize); public const string NumberOfBlocks = nameof(NumberOfBlocks); public const string OtherErrorDescription = nameof(OtherErrorDescription); public const string PowerManagementCapabilities = nameof(PowerManagementCapabilities); public const string PowerManagementSupported = nameof(PowerManagementSupported); public const string Purpose = nameof(Purpose); public const string ReadPolicy = nameof(ReadPolicy); public const string ReplacementPolicy = nameof(ReplacementPolicy); public const string StartingAddress = nameof(StartingAddress); public const string StatusInfo = nameof(StatusInfo); public const string SupportedSRAM = nameof(SupportedSRAM); public const string SystemCreationClassName = nameof(SystemCreationClassName); public const string SystemLevelAddress = nameof(SystemLevelAddress); public const string SystemName = nameof(SystemName); public const string WritePolicy = nameof(WritePolicy);
}
