<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.Core\Crystal.Infrastructure.Core.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.Wpf\Crystal.Infrastructure.Wpf.csproj" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\Crystal.Service.Storage\Crystal.Service.Storage.csproj" />
    <ProjectReference Include="..\..\Providers\Crystal.Provider.Mmi\Crystal.Provider.Mmi.csproj" />
    <ProjectReference Include="..\..\UI\Crystal.Resources\Crystal.Resources.csproj" />
    <ProjectReference Include="..\..\UI\Crystal.Controls\Crystal.Controls.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.Constants\Crystal.Infrastructure.Constants.csproj" />
  </ItemGroup>

  <Import Project="..\..\Infrastructures\Crystal.Infrastructure.Wpf\build\Crystal.Wpf.Usings.props" />

</Project>
