<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IntermediateOutputPath>$(SolutionDir)\Build\Intermediate\</IntermediateOutputPath>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Version>2.1.0.2</Version>
    <Authors>Jin Hu</Authors>
    <Description></Description>
    <PackageProjectUrl>https://github.com/jinhuca/Crystal.Plot2D</PackageProjectUrl>
    <PackageIcon>CrystalPlot2D.png</PackageIcon>
    <PackageTags>.NET;Visualization</PackageTags>
    <IntermediateOutputPath>$(SolutionDir)\Build\Intermediate\</IntermediateOutputPath>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <OutputPath>bin\debug</OutputPath>
    <BaseIntermediateOutputPath>obj\</BaseIntermediateOutputPath>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <LangVersion>latest</LangVersion>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DefineConstants>TRACE;CODE_ANALYSIS</DefineConstants>
    <DocumentationFile>
    </DocumentationFile>
    <OutputPath>bin\release</OutputPath>
    <BaseIntermediateOutputPath>obj\release</BaseIntermediateOutputPath>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <DebugSymbols>true</DebugSymbols>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'ReleaseXBAP|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\Output\</OutputPath>
    <DefineConstants>TRACE;CODE_ANALYSIS, RELEASEXBAP</DefineConstants>
    <DocumentationFile>
    </DocumentationFile>
    <Optimize>true</Optimize>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="bin\**" />
    <Compile Remove="Descriptions\**" />
    <Compile Remove="Isolines\**" />
    <Compile Remove="LegendItems\**" />
    <Compile Remove="Navigation\**" />
    <Compile Remove="obj\**" />
    <EmbeddedResource Remove="bin\**" />
    <EmbeddedResource Remove="Descriptions\**" />
    <EmbeddedResource Remove="Isolines\**" />
    <EmbeddedResource Remove="LegendItems\**" />
    <EmbeddedResource Remove="Navigation\**" />
    <EmbeddedResource Remove="obj\**" />
    <None Remove="bin\**" />
    <None Remove="Descriptions\**" />
    <None Remove="Isolines\**" />
    <None Remove="LegendItems\**" />
    <None Remove="Navigation\**" />
    <None Remove="obj\**" />
    <Page Remove="bin\**" />
    <Page Remove="Descriptions\**" />
    <Page Remove="Isolines\**" />
    <Page Remove="LegendItems\**" />
    <Page Remove="Navigation\**" />
    <Page Remove="obj\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
    <Reference Update="UIAutomationProvider">
      <RequiredTargetFramework>3.0</RequiredTargetFramework>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\SaveIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\FitToViewIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\CopyScreenshotIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\HelpIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\D3-icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\D3-icon-white.ico" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Toolbox\ChartPlotter.Icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
    <Compile Remove="Axes\DateTimeTicksProvider.cs" />
    <Compile Remove="Axes\DateTimeTicksProviderBase.cs" />
    <Compile Remove="Axes\DefaultNumericTicksProvider.cs" />
    <Compile Remove="Charts\Legend.xaml.cs" />
    <Compile Remove="Charts\LegendItem.cs" />
    <Compile Remove="Charts\LineLegendItem.xaml.cs" />
    <Compile Remove="Charts\MarkerPointGraph.cs" />
    <Compile Remove="Common\BindableBase.cs" />
    <Compile Remove="Common\ObservableUIElementCollection.cs" />
    <Compile Remove="Common\Plotter.xaml.cs" />
    <Compile Remove="Common\PropertySupport.cs" />
    <Compile Remove="InjectedPlotter.cs" />
    <Compile Remove="InjectedPlotterVerticalSyncConverter.cs" />
    <Compile Remove="Properties\Resources.Designer.cs" />
    <Compile Remove="Strings\Exceptions.ru-ru.Designer.cs" />
    <Compile Remove="Strings\UIResources.ru-ru.Designer.cs" />
    <EmbeddedResource Remove="Properties\Resources.resx" />
    <EmbeddedResource Remove="Strings\Exceptions.ru-ru.resx" />
    <EmbeddedResource Remove="Strings\UIResources.ru-ru.resx" />
    <None Remove="Resources\CrystalPlot2D.png" />
    <Page Remove="Charts\Legend.xaml" />

    <!-- Additional removes: Isoline-related sources and resources -->
    <Compile Remove="Charts\Isoline.cs" />
    <Compile Remove="Charts\IsolineRenderer.cs" />
    <Compile Remove="Charts\IsolineSeries.cs" />
    <Compile Remove="Charts\IsolineControl.xaml.cs" />
    <Page Remove="Charts\IsolineControl.xaml" />
    <Page Remove="Charts\LineLegendItem.xaml" />
    <EmbeddedResource Remove="Resources\LegendIcon.png" />
    <EmbeddedResource Remove="Resources\IsolineTexture.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\CrystalPlot2D.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Shapes\RangeHighlightStyle.xaml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <Generator>XamlIntelliSenseFileGenerator</Generator>
    </Page>
  </ItemGroup>
</Project>
