<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Crystal.Provider.CpuId</RootNamespace>
    <AssemblyName>Crystal.Provider.CpuId</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.DataStructures\Crystal.Infrastructure.DataStructures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Crystal.Provider.CpuId.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
