namespace Crystal.Mmi.HardwareFeatures.USBHub;

public record USBHubMetrics(
  ushort? Availability,
  string? Caption,
  byte? ClassCode,
  uint? ConfigManagerErrorCode,
  bool? ConfigManagerUserConfig,
  string? CreationClassName,
  byte[]? CurrentAlternateSettings,
  byte? CurrentConfigValue,
  string? Description,
  string? DeviceID,
  bool? ErrorCleared,
  string? ErrorDescription,
  bool? GangSwitched,
  DateTime? InstallDate,
  uint? LastErrorCode,
  string? Name,
  byte? NumberOfConfigs,
  byte? NumberOfPorts,
  string? PNPDeviceID,
  ushort[]? PowerManagementCapabilities,
  bool? PowerManagementSupported,
  byte? ProtocolCode,
  string? Status,
  ushort? StatusInfo,
  byte? SubclassCode,
  string? SystemCreationClassName,
  string? SystemName,
  ushort? USBVersion
);
