<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Unity" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Services\Crystal.Service.Process\Crystal.Service.Process.csproj" />
    <ProjectReference Include="..\..\Providers\Crystal.Provider.Mmi\Crystal.Provider.Mmi.csproj" />
    <ProjectReference Include="..\..\Providers\Crystal.Provider.Etw\Crystal.Provider.Etw.csproj" />
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.Constants\Crystal.Infrastructure.Constants.csproj" />
    <ProjectReference Include="..\..\UI\Crystal.Resources\Crystal.Resources.csproj" />
    <ProjectReference Include="..\..\UI\Crystal.Controls\Crystal.Controls.csproj" />
  </ItemGroup>

</Project>
