<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Prism.Core" Version="9.0.537" />
    <PackageReference Include="Prism.Unity" Version="9.0.537" />
    <PackageReference Include="Prism.Wpf" Version="9.0.537" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
    <Folder Include="ViewModels\" />
    <Folder Include="Views\" />
  </ItemGroup>

</Project>
