<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Bios\" />
    <Folder Include="Gpu\" />
    <Folder Include="Memory\" />
    <Folder Include="Network\" />
    <Folder Include="Sensors\" />
    <Folder Include="Storage\" />
  </ItemGroup>

</Project>
