namespace Crystal.Mmi.HardwareFeatures.PointingDevice;

public record PointingDeviceMetrics(
  ushort? Availability,
  string? Caption,
  uint? ConfigManagerErrorCode,
  bool? ConfigManagerUserConfig,
  string? CreationClassName,
  string? Description,
  string? DeviceID,
  ushort? DeviceInterface,
  uint? DoubleSpeedThreshold,
  bool? ErrorCleared,
  string? ErrorDescription,
  ushort? Handedness,
  string? HardwareType,
  string? InfFileName,
  string? InfSection,
  DateTime? InstallDate,
  bool? IsLocked,
  uint? LastErrorCode,
  string? Manufacturer,
  string? Name,
  byte? NumberOfButtons,
  string? PNPDeviceID,
  ushort? PointingType,
  ushort[]? PowerManagementCapabilities,
  bool? PowerManagementSupported,
  uint? QuadSpeedThreshold,
  uint? Resolution,
  uint? SampleRate,
  string? Status,
  ushort? StatusInfo,
  uint? Synch,
  string? SystemCreationClassName,
  string? SystemName
);
