namespace CrystalMonitorLib.Smbios.Structures;

// DMTF DSP0134 §7 — Structure type codes
public enum SmbiosStructureType : byte
{
    BiosInformation        = 0,
    SystemInformation      = 1,
    BaseboardInformation   = 2,
    ChassisInformation     = 3,
    ProcessorInformation   = 4,
    MemoryController       = 5,   // obsolete
    MemoryModule           = 6,   // obsolete
    CacheInformation       = 7,
    PortConnector          = 8,
    SystemSlots            = 9,
    OnBoardDevices         = 10,  // obsolete
    OemStrings             = 11,
    SystemConfigOptions    = 12,
    BiosLanguage           = 13,
    GroupAssociations      = 14,
    SystemEventLog         = 15,
    PhysicalMemoryArray    = 16,
    MemoryDevice           = 17,
    MemoryErrorInfo32      = 18,
    MemoryArrayMappedAddr  = 19,
    MemoryDeviceMappedAddr = 20,
    BuiltInPointingDevice  = 21,
    PortableBattery        = 22,
    SystemReset            = 23,
    HardwareSecurity       = 24,
    SystemPowerControls    = 25,
    VoltageProbe           = 26,
    CoolingDevice          = 27,
    TemperatureProbe       = 28,
    ElectricalCurrentProbe = 29,
    OutOfBandRemoteAccess  = 30,
    BootIntegrityServices  = 31,
    SystemBoot             = 32,
    MemoryErrorInfo64      = 33,
    ManagementDevice       = 34,
    ManagementDeviceComponent = 35,
    ManagementDeviceThreshold = 36,
    MemoryChannel          = 37,
    IpmiDevice             = 38,
    SystemPowerSupply      = 39,
    Additional             = 40,
    OnboardDevicesExtended = 41,
    ManagementControllerHostInterface = 42,
    TpmDevice              = 43,
    ProcessorAdditional    = 44,
    FirmwareInventory      = 45,
    StringProperty         = 46,
    Inactive               = 126,
    EndOfTable             = 127,
}
