<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Crystal.Service.Storage</RootNamespace>
    <AssemblyName>Crystal.Service.Storage</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="7.0.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructures\Crystal.Infrastructure.DataStructures\Crystal.Infrastructure.DataStructures.csproj" />
    <ProjectReference Include="..\..\Providers\Crystal.Provider.Mmi\Crystal.Provider.Mmi.csproj" />
    <ProjectReference Include="..\..\Providers\Crystal.Provider.Telemetry\Crystal.Provider.Telemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Crystal.Service.Storage.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
