using System;
using System.Collections.Generic;
using System.Text;

namespace Crystal.Mmi.Constants; 
internal static class ProcessConstants {
  public const string QueryString = "SELECT * FROM Win32_Process";

  public const string CaptionKey = "Caption";
  public const string CaptionDesc = "Short description of the process";

  public const string CommandLineKey = "CommandLine";
  public const string CommandLineDesc = "Command line used to start the process, if applicable";

  public const string CreationClassNameKey = "CreationClassName";
  public const string CreationClassNameDesc = "Name of the first concrete class to appear in the inheritance chain";

  public const string CreationDateKey = "CreationDate";
  public const string CreationDateDesc = "Date the process began executing";

  public const string DescriptionKey = "Description";
  public const string DescriptionDesc = "Description of the process";

  public const string ExecutablePathKey = "ExecutablePath";
  public const string ExecutablePathDesc = "Path to the executable file of the process";

  public const string ExecutionStateKey = "ExecutionState";
  public const string ExecutionStateDesc = "Current execution state of the process";

  public const string HandleKey = "Handle";
  public const string HandleDesc = "Process identifier (PID), represented as a string";

  public const string HandleCountKey = "HandleCount";
  public const string HandleCountDesc = "Total number of open handles owned by the process";

  public const string InstallDateKey = "InstallDate";
  public const string InstallDateDesc = "Date and time the process was installed";

  public const string KernelModeTimeKey = "KernelModeTime";
  public const string KernelModeTimeDesc = "Time, in 100-nanosecond units, spent executing in kernel mode";

  public const string MaximumWorkingSetSizeKey = "MaximumWorkingSetSize";
  public const string MaximumWorkingSetSizeDesc = "Maximum working set size of the process, in bytes";

  public const string MinimumWorkingSetSizeKey = "MinimumWorkingSetSize";
  public const string MinimumWorkingSetSizeDesc = "Minimum working set size of the process, in bytes";

  public const string NameKey = "Name";
  public const string NameDesc = "Name of the executable file responsible for the process";

  public const string PageFaultsKey = "PageFaults";
  public const string PageFaultsDesc = "Number of page faults generated by the process";

  public const string PageFileUsageKey = "PageFileUsage";
  public const string PageFileUsageDesc = "Amount of page file space, in kilobytes, currently used by the process";

  public const string ParentProcessIdKey = "ParentProcessId";
  public const string ParentProcessIdDesc = "Process identifier (PID) of the process's creator";

  public const string PeakPageFileUsageKey = "PeakPageFileUsage";
  public const string PeakPageFileUsageDesc = "Peak page file space used, in kilobytes, by the process";

  public const string PeakVirtualSizeKey = "PeakVirtualSize";
  public const string PeakVirtualSizeDesc = "Peak virtual address space used by the process, in bytes";

  public const string PeakWorkingSetSizeKey = "PeakWorkingSetSize";
  public const string PeakWorkingSetSizeDesc = "Peak working set size of the process, in bytes";

  public const string PriorityKey = "Priority";
  public const string PriorityDesc = "Scheduling priority of the process's threads";

  public const string PrivatePageCountKey = "PrivatePageCount";
  public const string PrivatePageCountDesc = "Current number of pages allocated exclusively for the process";

  public const string ProcessIdKey = "ProcessId";
  public const string ProcessIdDesc = "Process identifier (PID) uniquely identifying the process on the system";

  public const string SessionIdKey = "SessionId";
  public const string SessionIdDesc = "Terminal Services session under which the process is running";

  public const string StatusKey = "Status";
  public const string StatusDesc = "Current status of the process";

  public const string TerminationDateKey = "TerminationDate";
  public const string TerminationDateDesc = "Date the process was stopped or terminated";

  public const string ThreadCountKey = "ThreadCount";
  public const string ThreadCountDesc = "Number of active threads in the process";

  public const string UserModeTimeKey = "UserModeTime";
  public const string UserModeTimeDesc = "Time, in 100-nanosecond units, spent executing in user mode";

  public const string VirtualSizeKey = "VirtualSize";
  public const string VirtualSizeDesc = "Current virtual address space size of the process, in bytes";

  public const string WorkingSetSizeKey = "WorkingSetSize";
  public const string WorkingSetSizeDesc = "Current working set size of the process, in bytes";
}
