<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Crystal.Mmi</RootNamespace>
    <AssemblyName>Crystal.Mmi</AssemblyName>
    <BaseOutputPath>$(SolutionDir)\Build\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
    <PackageReference Include="Prism.Core" Version="9.0.537" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Crystal.Mmi.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
